### PR TITLE
Some works on i18n

### PR DESCRIPTION
**Pull request by moesoha**
I did some work on i18n just now, I've added a Chinese translation on Command Palettes as a preview.

snipaste_2018-08-29_23-08-42

Please review the codes and tell me if it is OK or something needs to be improved.

Of course, I will do the Chinese (Simplified) translation for the plugin after the pr merged. 😄

### CODE REVIEW

**Comment by ThadHouse** [comment]
This is all combined into a single extension .VSIX file right? It's not separate publishes per language?

**Comment by moesoha** [comment]
yes. It switches with the vscode's locale setting.

**Comment by ThadHouse** [comment]
CI is giving unhandled promise exceptions during the gulp build.
https://ci.appveyor.com/project/wpilibsuite/vscode-wpilib/build/master-89-hyafavgv

**Comment by moesoha** [comment]
I will check that. 12:48 AM here, go sleep now.

**Comment by ThadHouse** [comment]
Nevermind was my fault. You'll need to rebase off of the newest master.

**Comment by moesoha** [comment]
Thanks for helping me upgrade `gulp`. I'm going to do more with i18n now.

**Pull request merged**
