### PR TITLE
Updates to enable robot code debugging for 2022

### PR DESCRIPTION
**Pull request by ThadHouse**
Depends on https://github.com/wpilibsuite/GradleRIO/pull/554

### CODE REVIEW

**Comment by sciencewhiz** [comment]
The combination of this PR and wpilibsuite/GradleRIO#554 fixed java debugging on the roboRIO, but C++ still failed.

```
2021-11-20T22:54:40.270Z verbose: executing command in workspace {"0":{"_args":[],"_commandLine":"gradlew deploy  -PdebugMode -PteamNumber=330 --offline  -Dorg.gradle.java.home=\"C:\\Users\\Public\\wpilib\\2022\\jdk\"","_options":{"cwd":"c:\\Users\\Joe\\Documents\\Robotics\\2022beta2CommandCpp","env":{"JAVA_HOME":"C:\\Users\\Public\\wpilib\\2022\\jdk"},"executable":"cmd.exe","shellArgs":["/d","/c"]}},"1":"c:\\Users\\Joe\\Documents\\Robotics\\2022beta2CommandCpp"}
2021-11-20T22:54:59.644Z verbose: [Locale] Loading message@en-us
2021-11-20T22:54:59.645Z error: [Locale] Failed to load message@en-us. {"0":{"errno":-4058,"syscall":"open","code":"ENOENT","path":"c:\\Users\\Public\\wpilib\\2022\\vscode\\data\\extensions\\wpilibsuite.vscode-wpilib-2022.1.1-beta-2-6-gd08521e\\i18n\\en-us\\message.json"}}
2021-11-20T22:54:59.646Z error: Debug error {"0":{"errno":-4058,"code":"ENOENT","syscall":"open","path":"c:\\Users\\Joe\\Documents\\Robotics\\2022beta2CommandCpp\\build\\debug\\debug_info.json"}}
```

**Comment by ThadHouse** [comment]
Is that debug_info.json file there?

**Comment by sciencewhiz** [comment]
No

**Review by sciencewhiz — APPROVED** [review]
It works after I used the right version of GradleRIO

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
